### ISSUE TITLE
Improve handshake process

### ISSUE THREAD

**Issue by diraol** [kytos/kyco-core-napps#12]
On the ``of.core`` napp some methods does not need to be 'listeners' since they can be called directly by other ``of.core`` methods.

For example, the "*Hello* handler" can be called directly by the method that creates the Hello event. The same occurs with the features_request 'handler'.

**Comment by beraldoleal** [comment]
@diraol , this was already fixed, right ?

**Comment by diraol** [comment]
Yes, I do think so! Thanks for the hardwork last week.

\o/

--------------------------------
Diego Rabatone Oliveira
http://blog.diraol.eng.br
diraol(arroba)diraol(ponto)eng(ponto)br
Twitter: @diraol

2016-10-03 9:42 GMT-03:00 Beraldo Leal <notifications@github.com>:
