### ISSUE TITLE
lldp topology discovery napp

### ISSUE THREAD

**Issue by beraldoleal** [kytos/kyco-core-napps#14]

**Comment by diraol** [comment]
[WIP] on branch "lldp"

**Comment by cemsbr** [comment]
@diraol, was this issue already addressed in another branch?

**Comment by diraol** [comment]
@cemsbr, @beraldoleal has done two commits[1] on this napp. I think that maybe this issue can be closed.
@beraldoleal can you confirm that this napp is already finished and it is working? ;)

[1] https://github.com/kytos/kyco-core-napps/commits/develop/kytos/of.lldp

**Comment by beraldoleal** [comment]
yes, is closed for now. thanks.
