### ISSUE TITLE
Statistics watch dog napp

### ISSUE THREAD

**Issue by beraldoleal** [kytos/kyco-core-napps#15]

**Comment by cemsbr** [comment]
Example for generating a graph in kytos/of.stats/rdd:

First, get the "first" and "last" useful timestamps with:
```bash
rrdtool fetch switch1port1.rrd AVERAGE | grep -v nan
```

Optionally, verify the records for the graph:
```bash
rrdtool fetch switch1port1.rrd AVERAGE --start [first-1] --end [last-1]
```

Then, make graph subtracting 1 from the first and last useful timestamps:
```bash
rrdtool graph speed.png --start [first-1] --end [last-1] \
DEF:speed=switch1port1.rrd:rx_bytes:AVERAGE LINE2:speed#FF0000
```
