### ISSUE TITLE
Create a complete kytos.json file for each napp

### ISSUE THREAD

**Issue by beraldoleal** [kytos/kyco-core-napps#17]
One issue created for each napp. This issue was changed to an Epic in which the new issues were referenced.

**Comment by cemsbr** [comment]
- [ ] of.core
- [ ] of.flow-manager
- [ ] of.ipv6disable
- [ ] of.l2ls
- [ ] of.l2lsloop
- [ ] of.liveness
- [ ] of.lldp
- [ ] of.stats
- [ ] of.topology

**Comment by cemsbr** [comment]
@beraldoleal, @diraol, what kind of dependencies are supposed to be in the kytos.json file? For example: python-openflow, kyco, rrdtool and python-rrdtool? Should we replicate the requirements.txt file or just add non-python software?

**Comment by beraldoleal** [comment]
@cemsbr  Theses dependencies are napps only. So if napp A depends on napp B , napp B goes here.

**Comment by diraol** [comment]
@beraldoleal and what if the napp depends on another python library (that is not a dependency of kyco itself)? Where should we register that dependency?

**Comment by cemsbr** [comment]
requirements.txt?

**Comment by diraol** [comment]
If I just want one napp from a specific repository, it does not seems
reasonable to me to install the requirements from all napps of that repo,
right?​
